# Generated by Django 4.2.5 on 2023-10-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_delete_eras_swifties_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swifties',
            new_name='Swiftie',
        ),
    ]
