# Generated by Django 4.2.5 on 2023-10-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_remove_swiftie_id_alter_swiftie_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swiftie',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='swiftie',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='swiftie',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='swiftie',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
