# Generated by Django 4.2.5 on 2023-10-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_rename_apellido_swiftie_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulsera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(choices=[('debut', 'Debut'), ('fearless', 'Fearless'), ('sn', 'Speak Now'), ('red', 'Red'), ('1989', '1989'), ('rep', 'Reputation'), ('lover', 'Lover'), ('folklore', 'Folklore'), ('evermore', 'Evermore'), ('midnights', 'Midnights')], max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugarConcierto', models.CharField(max_length=20)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('fotoPulsera', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.swiftie')),
            ],
            options={
                'ordering': ['autor', '-fechaPublicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='BlogApp.era')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
