# Generated by Django 4.2.5 on 2023-10-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_rename_apellido_pulsera_album_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pulsera',
            new_name='mil989',
        ),
    ]
