# Generated by Django 4.2.5 on 2023-10-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0008_rename_pulsera_mil989'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='mil989',
        ),
        migrations.AlterModelOptions(
            name='era',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
        migrations.RemoveField(
            model_name='era',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='era',
            name='fotoPulsera',
        ),
        migrations.RemoveField(
            model_name='era',
            name='lugarConcierto',
        ),
        migrations.AddField(
            model_name='era',
            name='imagenPulsera',
            field=models.ImageField(default='', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='era',
            name='pais',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='era',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='era',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='era',
            name='era',
            field=models.CharField(choices=[('debut', 'Debut'), ('speaknow', 'Speak now'), ('fearless', 'Fearless'), ('red', 'Red'), ('1989', '1989'), ('reputation', 'Reputation'), ('lover', 'Lover'), ('folklore', 'Folklore'), ('evermore', 'Evermore'), ('midnights', 'Midnights')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Swiftie',
        ),
        migrations.AddField(
            model_name='era',
            name='colores',
            field=models.ManyToManyField(to='BlogApp.colores'),
        ),
    ]
