# Generated by Django 4.2.5 on 2023-10-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_remove_colores_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='era',
            name='colores',
        ),
        migrations.DeleteModel(
            name='Colores',
        ),
    ]
