# Generated by Django 4.2.5 on 2023-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_remove_era_colores_delete_colores'),
    ]

    operations = [
        migrations.AddField(
            model_name='era',
            name='colorPredominante',
            field=models.CharField(default='blanco', max_length=10),
        ),
    ]
