# Generated by Django 4.2.5 on 2023-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_era_colorpredominante'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulsera1989',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('era', models.CharField(blank=True, max_length=40, null=True)),
                ('colorPredominante', models.CharField(default='blanco', max_length=10)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPulsera', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='pulseraFolklore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('era', models.CharField(blank=True, max_length=40, null=True)),
                ('colorPredominante', models.CharField(default='blanco', max_length=10)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPulsera', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='pulseraLover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('era', models.CharField(blank=True, max_length=40, null=True)),
                ('colorPredominante', models.CharField(default='blanco', max_length=10)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPulsera', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='pulseraReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('era', models.CharField(blank=True, max_length=40, null=True)),
                ('colorPredominante', models.CharField(default='blanco', max_length=10)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPulsera', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='pulseraSpeakNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('era', models.CharField(blank=True, max_length=40, null=True)),
                ('colorPredominante', models.CharField(default='blanco', max_length=10)),
                ('pais', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPulsera', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.AlterField(
            model_name='era',
            name='era',
            field=models.CharField(choices=[('speaknow', 'Speak now'), ('1989', '1989'), ('reputation', 'Reputation'), ('lover', 'Lover'), ('folklore', 'Folklore')], max_length=15, null=True),
        ),
    ]
