# Generated by Django 4.2.5 on 2023-10-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_pulsera1989_pulserafolklore_pulseralover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='era',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='colorPredominante',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='era',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='imagenPulsera',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='pulsera1989',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='colorPredominante',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='era',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='imagenPulsera',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='pulserafolklore',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='colorPredominante',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='era',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='imagenPulsera',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='pulseralover',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='colorPredominante',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='era',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='imagenPulsera',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='pulserareputation',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='colorPredominante',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='era',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='imagenPulsera',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='pulseraspeaknow',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pulsera1989',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='pulsera1989',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pulserafolklore',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='pulserafolklore',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pulseralover',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='pulseralover',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pulserareputation',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='pulserareputation',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pulseraspeaknow',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='pulseraspeaknow',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulsera1989',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pulserafolklore',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pulseralover',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pulserareputation',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pulseraspeaknow',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Era',
        ),
    ]
