# Generated by Django 4.2.5 on 2023-10-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_usuario_remove_era_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsera1989',
            name='color_predominante',
            field=models.CharField(default='Blanco', max_length=30),
        ),
        migrations.AddField(
            model_name='pulserafolklore',
            name='color_predominante',
            field=models.CharField(default='Blanco', max_length=30),
        ),
        migrations.AddField(
            model_name='pulseralover',
            name='color_predominante',
            field=models.CharField(default='Blanco', max_length=30),
        ),
        migrations.AddField(
            model_name='pulserareputation',
            name='color_predominante',
            field=models.CharField(default='Blanco', max_length=30),
        ),
        migrations.AddField(
            model_name='pulseraspeaknow',
            name='color_predominante',
            field=models.CharField(default='Blanco', max_length=30),
        ),
        migrations.AlterField(
            model_name='pulsera1989',
            name='edad',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='pulserafolklore',
            name='edad',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='pulseralover',
            name='edad',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='pulserareputation',
            name='edad',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='pulseraspeaknow',
            name='edad',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
