# Generated by Django 4.2.5 on 2023-10-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_pulsera1989_color_predominante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pulseraSpeakNow',
        ),
    ]
