# Generated by Django 4.2.5 on 2023-10-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0017_pulsera1989_imagen_pulserafolklore_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
